### ISSUE TITLE
您好，hexo博客关于音乐盒，按照您的教程来的但是不起作用，可以看看您具体的配置吗

### ISSUE THREAD

**Issue by gscgoon** [Feiju12138/Feiju12138.github.io#7]

**Comment by feiju12138** [comment]
![01.png](https://inews.gtimg.com/newsapp_ls/0/14251468226/0.png)
![02.png](https://inews.gtimg.com/newsapp_ls/0/14251468536/0.png)
![03.png](https://inews.gtimg.com/newsapp_ls/0/14251468730/0.png)
![04.png](https://inews.gtimg.com/newsapp_ls/0/14251468737/0.png)
![05.png](https://inews.gtimg.com/newsapp_ls/0/14251468742/0.png)
![06.png](https://inews.gtimg.com/newsapp_ls/0/14251468740/0.png)
[APlayer的官方说明文档](https://aplayer.js.org/#/zh-Hans/)

**Comment by gscgoon** [comment]
您好，加载的是所有信息，但不是音乐盒的形式，也不能点击播放，为啥呀，苦笑

**Comment by feiju12138** [comment]
有可能是APlayer的配置有误，应该参照官方文档创建JS对象
[APlayer的官方文档](https://aplayer.js.org/#/zh-Hans/)
你应该检查一下浏览器的控制台，看看是什么报错，你可以在评论区发一张截图

**Comment by gscgoon** [comment]
![博客报错](https://user-images.githubusercontent.com/42020126/144747090-a75b6afb-905b-478c-a590-238c9364b8f5.png)

**Comment by gscgoon** [comment]
![博客音乐盒样式问题](https://user-images.githubusercontent.com/42020126/144748689-2e8b916e-8284-4d10-8030-952cde1d0735.png)
不好意思，刚才又看了下是可以通过这个播放的，是样式问题，但不知道怎么解决，前端不太懂

**Comment by gscgoon** [comment]
![音乐盒显示问题](https://user-images.githubusercontent.com/42020126/144751273-9557fa94-e39b-46e4-84e6-3d26c5fef16a.png)
我从APlayer的官方文档重新安装了1.10.1版本的可以了，使用scheme: Gemini显示有些问题，您知道这块应该如何修改吗，谢谢

**Comment by feiju12138** [comment]
有可能是侧边栏的宽度有点窄，导致图标被挤下去了，你可以尝试放在别的区域试一试，看看还会不会出现这个情况，以判定是不是因为宽度造成的问题

**Comment by gscgoon** [comment]
试了，好像不行，scheme换成Muse和Mist这两种主题就可以正常显示

**Comment by feiju12138** [comment]
那应该是CSS冲突了，你可以试一试把引入APlayer的CSS代码放在尽量放在NexT的CSS后面。或者你可以尝试把APlayer的所有相关代码放在一个新的HTML中，然后在主页使用iframe标签将调试好的，没有问题的APlayer页面引入到主页

**Comment by gscgoon** [comment]
![报错](https://user-images.githubusercontent.com/42020126/144867635-4c983caf-c689-4afc-8f72-e9a3e8eb0a04.png)
谢谢问题已解决，但是控制台之前一直报这个错，是因为啥呢

**Comment by feiju12138** [comment]
因为CDN中的pace-js这个模块出了问题，引入的页面找不到了，所以报了404
